// Generated by CoffeeScript 1.10.0
var CrowdControl, r, riot;

r = require('./riot');

riot = r();

CrowdControl = {
  Views: require('./views'),
  tags: [],
  start: function(opts) {
    return this.tags = riot.mount('*', opts);
  },
  update: function() {
    var i, len, ref, results, tag;
    ref = this.tags;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      tag = ref[i];
      results.push(tag.update());
    }
    return results;
  },
  riot: r
};

if (module.exports != null) {
  module.exports = CrowdControl;
}

if (typeof window !== "undefined" && window !== null) {
  if (window.Crowdstart != null) {
    window.Crowdstart.Crowdcontrol = CrowdControl;
  } else {
    window.Crowdstart = {
      CrowdControl: CrowdControl
    };
  }
}

//# sourceMappingURL=index.js.map
