// Generated by CoffeeScript 1.10.0
var r;

r = function() {
  return r.riot;
};

r.set = function(riot) {
  return r.riot = riot;
};

r.riot = typeof window !== "undefined" && window !== null ? window.riot : void 0;

module.exports = r;

//# sourceMappingURL=riot.js.map
