// Generated by CoffeeScript 1.10.0
var log;

log = function() {
  if (log.DEBUG) {
    return console.log.apply(console, arguments);
  }
};

log.DEBUG = false;

log.debug = log;

log.info = function() {
  return console.log.apply(console, arguments);
};

log.warn = function() {
  console.log('WARN:');
  return console.log.apply(console, arguments);
};

log.error = function() {
  console.log('ERROR:');
  console.log.apply(console, arguments);
  throw new arguments[0];
};

module.exports = log;

//# sourceMappingURL=log.js.map
