// Generated by CoffeeScript 1.10.0
var promise, xhr;

promise = require('bluebird');

xhr = require('xhr-promise');

Function.prototype.property = function(prop, desc) {
  return Object.defineProperty(this.prototype, prop, desc);
};

promise["new"] = function(fn) {
  return new promise(fn);
};

module.exports = {
  observable: function(obj) {
    return this.riot.observable(obj);
  },
  requestAnimationFrame: require('raf'),
  riot: (typeof window !== "undefined" && window !== null) && (window.riot != null) ? window.riot : void 0,
  xhr: function(data) {
    var x;
    x = new xhr();
    return x.send.apply(x, arguments);
  },
  promise: promise
};

//# sourceMappingURL=shim.js.map
